import type { Metadata } from "next";
import { Geist, Geist_Mono, Space_Grotesk, Ubuntu } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import QueryProviders from "@/providers/QueryProvider";
import { Toaster } from "@/components/ui/sonner";
import { SelectedIconsProvider } from "@/context/SelectedIconsContext";

const spaceGroteskHeading = Space_Grotesk({subsets:['latin'],variable:'--font-heading'});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
  style: ["normal", "italic"],
  variable: "--font-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", geistSans.variable, geistMono.variable, ubuntu.variable, "font-sans", spaceGroteskHeading.variable)}
    >

    
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
         <SelectedIconsProvider>
          <QueryProviders>
          {children}
          <Toaster position="top-right" richColors />
        </QueryProviders>
         </SelectedIconsProvider>

        
        
    </body>
    </html>
  );
}
